# Shared minimal GDAL configuration for desktop runtime artifacts.
set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_APPS ON CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_PYTHON_BINDINGS OFF CACHE BOOL "" FORCE)
set(BUILD_JAVA_BINDINGS OFF CACHE BOOL "" FORCE)
set(BUILD_CSHARP_BINDINGS OFF CACHE BOOL "" FORCE)
set(GDAL_BUILD_OPTIONAL_DRIVERS OFF CACHE BOOL "" FORCE)
set(OGR_BUILD_OPTIONAL_DRIVERS OFF CACHE BOOL "" FORCE)

# Only formats required by the current pipeline.
set(GDAL_ENABLE_DRIVER_VRT ON CACHE BOOL "" FORCE)
set(GDAL_ENABLE_DRIVER_GTIFF ON CACHE BOOL "" FORCE)
set(GDAL_ENABLE_DRIVER_PNG ON CACHE BOOL "" FORCE)
set(GDAL_ENABLE_DRIVER_JPEG OFF CACHE BOOL "" FORCE)
set(GDAL_ENABLE_DRIVER_WEBP OFF CACHE BOOL "" FORCE)

# Prefer a small, auditable dependency surface.
set(GDAL_USE_EXTERNAL_LIBS OFF CACHE BOOL "" FORCE)
set(GDAL_USE_INTERNAL_LIBS ON CACHE BOOL "" FORCE)
set(GDAL_USE_PROJ ON CACHE BOOL "" FORCE)
set(GDAL_USE_ZLIB ON CACHE BOOL "" FORCE)
# Keep zstd disabled so macOS builds cannot inherit a Homebrew dylib path.
# GTiff/PNG remain enabled through GDAL's bundled libraries.
set(GDAL_USE_ZSTD OFF CACHE BOOL "" FORCE)
set(GDAL_USE_LIBTIFF ON CACHE BOOL "" FORCE)
set(GDAL_USE_LIBGEOTIFF ON CACHE BOOL "" FORCE)
set(GDAL_USE_PNG ON CACHE BOOL "" FORCE)
set(GDAL_USE_JPEG OFF CACHE BOOL "" FORCE)
set(GDAL_USE_WEBP OFF CACHE BOOL "" FORCE)

# Network and database drivers are deliberately excluded.
set(GDAL_USE_CURL OFF CACHE BOOL "" FORCE)
set(GDAL_USE_OPENSSL OFF CACHE BOOL "" FORCE)
set(GDAL_USE_SQLITE3 OFF CACHE BOOL "" FORCE)
set(GDAL_USE_GEOS OFF CACHE BOOL "" FORCE)
set(GDAL_USE_POSTGRESQL OFF CACHE BOOL "" FORCE)
set(GDAL_USE_ARROW OFF CACHE BOOL "" FORCE)
set(GDAL_USE_HDF5 OFF CACHE BOOL "" FORCE)
set(GDAL_USE_NETCDF OFF CACHE BOOL "" FORCE)
set(GDAL_USE_POPPLER OFF CACHE BOOL "" FORCE)
